# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctrl_buf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctrl_buf.proto',
  package='emulator_control',
  serialized_pb=_b('\n\x0e\x63trl_buf.proto\x12\x10\x65mulator_control\"Z\n\x07\x43ontrol\x12\x0b\n\x03\x63md\x18\x01 \x02(\t\x12\x0b\n\x03non\x18\x02 \x01(\x05\x12\r\n\x05ports\x18\x03 \x03(\x05\x12\x0b\n\x03loc\x18\x04 \x03(\x05\x12\x0b\n\x03seq\x18\x05 \x01(\x08\x12\x0c\n\x04rloc\x18\x06 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTROL = _descriptor.Descriptor(
  name='Control',
  full_name='emulator_control.Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='emulator_control.Control.cmd', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='non', full_name='emulator_control.Control.non', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ports', full_name='emulator_control.Control.ports', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loc', full_name='emulator_control.Control.loc', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='emulator_control.Control.seq', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rloc', full_name='emulator_control.Control.rloc', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['Control'] = _CONTROL

Control = _reflection.GeneratedProtocolMessageType('Control', (_message.Message,), dict(
  DESCRIPTOR = _CONTROL,
  __module__ = 'ctrl_buf_pb2'
  # @@protoc_insertion_point(class_scope:emulator_control.Control)
  ))
_sym_db.RegisterMessage(Control)


# @@protoc_insertion_point(module_scope)
