# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_buf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_buf.proto',
  package='node_data_feed',
  serialized_pb=_b('\n\x0e\x64\x61ta_buf.proto\x12\x0enode_data_feed\"\x13\n\x04Send\x12\x0b\n\x03nop\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEND = _descriptor.Descriptor(
  name='Send',
  full_name='node_data_feed.Send',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nop', full_name='node_data_feed.Send.nop', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['Send'] = _SEND

Send = _reflection.GeneratedProtocolMessageType('Send', (_message.Message,), dict(
  DESCRIPTOR = _SEND,
  __module__ = 'data_buf_pb2'
  # @@protoc_insertion_point(class_scope:node_data_feed.Send)
  ))
_sym_db.RegisterMessage(Send)


# @@protoc_insertion_point(module_scope)
