# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet_format

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet_format',
  package='packet',
  syntax='proto2',
  serialized_pb=_b('\n\rpacket_format\x12\x06packet\"E\n\x0bremove_node\x12\x0b\n\x03\x63md\x18\x01 \x02(\t\x12\x11\n\tnode_addr\x18\x02 \x01(\x03\x12\x16\n\x0elistening_port\x18\x03 \x02(\x05')
)




_REMOVE_NODE = _descriptor.Descriptor(
  name='remove_node',
  full_name='packet.remove_node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='packet.remove_node.cmd', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_addr', full_name='packet.remove_node.node_addr', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='listening_port', full_name='packet.remove_node.listening_port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['remove_node'] = _REMOVE_NODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

remove_node = _reflection.GeneratedProtocolMessageType('remove_node', (_message.Message,), dict(
  DESCRIPTOR = _REMOVE_NODE,
  __module__ = 'packet_format_pb2'
  # @@protoc_insertion_point(class_scope:packet.remove_node)
  ))
_sym_db.RegisterMessage(remove_node)


# @@protoc_insertion_point(module_scope)
